# ======================== 基础配置 ========================
## 安装目录
DAYTONA_BASE=/opt
## 服务端口
DAYTONA_PORT=3000
## Dashboard 端口（与 API 共用 3000）
## Docker 网段设置
DAYTONA_DOCKER_SUBNET=172.31.250.192/26

# ======================== 数据库配置 ========================
## 是否使用外部数据库
DAYTONA_EXTERNAL_DB=false
## 数据库地址（外部数据库时填写）
DB_HOST=db
## 数据库端口
DB_PORT=5432
## 数据库用户名
DB_USERNAME=user
## 数据库密码
DB_PASSWORD=pass
## 数据库名
DB_DATABASE=daytona

# ======================== Redis 配置 ========================
## 是否使用外部 Redis
DAYTONA_EXTERNAL_REDIS=false
## Redis 地址（外部 Redis 时填写）
REDIS_HOST=redis
## Redis 端口
REDIS_PORT=6379

# ======================== 对象存储配置 ========================
## MinIO 访问 Key
S3_ACCESS_KEY=minioadmin
## MinIO 密钥
S3_SECRET_KEY=minioadmin
## MinIO 端口
MINIO_PORT=9001

# ======================== 镜像仓库配置 ========================
## Registry 管理员用户名
REGISTRY_ADMIN=admin
## Registry 管理员密码
REGISTRY_PASSWORD=password

# ======================== 镜像配置 ========================
## 版本号
DAYTONA_VERSION=v0.0.1
